spring:
  profiles:
    active: dev
  application:
    name: u-short
  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
app:
  base-url: http://localhost:8080
server:
  port: 8080