spring:
  config:
    activate:
      on-profile: dev
  task:
    execution:
      pool:
        core-size: 8
        max-size: 20
        keep-alive: 10s
        queue-capacity: 50
      thread-name-prefix: dev-
  datasource:
    url: 'jdbc:postgresql://localhost:5432/u_short_db'
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
app:
  base-url: ${APP_BASE_URL:http://localhost:8080}